### ISSUE TITLE
Add some "examples"

### ISSUE THREAD

**Issue by misaon** [nittro/nittro#10]
Pls add some "examples" how use simple jQuery plugin with Nittro. I like it. :)

**Comment by jahudka** [comment]
Hi, I'm working on a cookbook which will address many of these simple use-case scenarios. Are you in a hurry? I'm hoping to make the cookbook available in stages over the next month, the first stage should hopefully be up within the week, but if you're in a hurry just try to describe the problem you're trying to solve and I'll be happy to help :-)

**Comment by Lumeriol** [comment]
Some news about Cookbook or documentation? :) It has been over year from announcing it at PoSobota ;)

**Comment by jahudka** [comment]
Yeah, I know... well, truth be told, not really. I did some work on it a week or so ago, but it's still quite far from ready and I'm stretched pretty thin :-(

**Comment by vylink** [comment]
Any progress? Can you just push me a little bit? I can write some doc of how to use Nittro with jQuery dependant plugins.
