### ISSUE TITLE
Datagrid

### ISSUE THREAD

**Issue by Bezdekm** [nittro/nittro#12]
There is at this moment at least one (any) fully functional dataGrid?

I've already tried Nextras\DataGrid, o5Grido, mesour\DataGrid, Ublabloo DataGrid, but nothing works.

Thanks :)

**Comment by jahudka** [comment]
Hi, as far as I know Nextras\DataGrid should work without any special adjustments, what issue did you encounter with it?

**Comment by jahudka** [comment]
Closing this for now as I don't have any feedback here.
