### ISSUE TITLE
Session not cleared

### ISSUE THREAD

**Issue by mabar** [nittro/nittro#16]
When no flashMessage is send, new Nette.Application.Flash key is created in session with inherited expiration instead of just a few seconds. Empty keys in session are stacked on every request.

Btw. After installing Nittro is *Delete whole session* button in [kdyby/nette-session-panel](https://github.com/fprochazka/Nette-Session-DebugBar) throwing `Use $presenter->sendPayload() instead of terminate() to send payload.`
Don't know if it's problem of this package.

**Comment by jahudka** [comment]
Hi, maybe the Nittro PresenterUtils trait is at fault here - it's calling `$presenter->getFlashSession()` without checking `$presenter->hasFlashSession()` first. Try updating `nittro/nette-bridges` to `v2.0.1`, that should help.

Unfortunately I haven't the slightest what may be causing the second error; I've never used [kdyby/nette-session-panel], but Nittro doesn't call `$presenter->terminate()` anywhere in the code, so I don't think it's Nittro's fault.

**Comment by mabar** [comment]
Thank you.

Weird on this bug is that session panel is not working with presenter. Error sometimes not appear and sometimes all styles and scripts on page dissapear after it. I'll look deeper into it. Seems like bug in tracy's ajax.
