### ISSUE TITLE
Tracy links

### ISSUE THREAD

**Issue by webrouse** [nittro/nittro#18]
Hi,

When I use Nittro in debug mode and **Tracy bluescreen will appear: so links that show dropdown information are unworkable**, when I click on a Tracy link, Nittro reloads the same page, but the dropdown information will not be displayed. In my opinion, there should be no reload at all.

I use this workaround to fix problems:
```js
....
// Ignore empty and Tracy links
builder
  .getServiceDefinition('page')
  .addSetup((page) => {
    page.on('transaction-created', (evt) => {
      const el = evt.data.context.element;
      if (el && el.tagName === 'A' && (!el.getAttribute('href') || el.getAttribute('data-tracy-ref'))) {
        evt.data.transaction.abort();
      }
    });
  });
...
```

--------------------------------------

The problem occurs only when the browser successfully load JavaScript (and also the Nittro, for example defined in HEAD).

* Nittro should work with Tracy out of the box
* It would be good to have a selector or callback (or both) to determine which links should be used with nittro-ajax (I did not find such setting.). Also it could automatically discard blank links that have no HREF attribute.

Thank you.

**Comment by jahudka** [comment]
Hi, again, sorry for getting back to you only now - thanks for the report, this is indeed a bug - it has been fixed now, try updating the `nittro-page` package to v2.0.15.

On another note, your workaround is almost correct, but it would have been better to use the `before-transaction` event to prevent certain links from being loaded using Nittro - the `transaction-created` event is intended as a hook for scripts processing the transaction when it has already been determined that the transaction _should_ be handled by Nittro. In a `before-transaction` event handler a transaction can be fully cancelled by calling `evt.preventDefault()`, or it can be postponed until a promise is resolved using `evt.waitFor(promise)` (this is what the Nittro Confirm widget uses). If you need to filter links that are handled by Nittro using a selector, you can do so within this handler. Alternatively you can use the [link whitelisting option](https://github.com/nittro/nittro/wiki/Controlling-Nittro-behaviour#default-configuration) along with `data-ajax="true"` if you only have a handful of links which should be handled by Nittro.
