### ISSUE TITLE
Allow use mangle option in uglify

### ISSUE THREAD

**Issue by mabar** [nittro/nittro#21]
Remove parsing of functions (simulating DI) with regex and use standard node_modules instead.
This DI simulation disallows rename functions with js compressor.

(I know you know it @jahudka. I writed it here just to stay informed, our slack channel is not good place to store issues)

**Comment by jahudka** [comment]
@mabar yeah, I'm planning this in the long term at least, but I'm not sure if such a huge change should be introduced in v2.x - and I know there's not that many users yet, but it would still break all of their custom code if it were just a minor release. I know I'm not very good at keeping nittro semantically versioned, but this would be pretty drastic even for my standards :-D so I think it'll have to wait until v3. Which is not to say it's gonna take years, but it also probably won't be anytime soon..

**Comment by mabar** [comment]
Chill, it is not must have feature. I would preffer completed docs to learn nittro more in depth. It could bring more of us to use this library

**Comment by jahudka** [comment]
That's very true.. but I'm hopeful that's gonna happen a bit earlier ;-)
