### ISSUE TITLE
Compatible declarations

### ISSUE THREAD

**Issue by Lumeriol** [nittro/nittro#23]
There are problems with compatible types in replaced files (Presenter, PresenterUtils) for newest versions of Nette (dev-version), i.e.

Declaration of Nittro\Bridges\NittroUI\Presenter::sendPayload() must be compatible with Nette\Application\UI\Presenter::sendPayload(): void

**Comment by jahudka** [comment]
Thanks for the report, I've created the 2.1-alpha release of the `nittro/nette-bridges` package which should be compatible with the 3.0 alphas of Nette, please try it out; if there are any bugs, please report them to the [`nittro/nette-bridges`](https://github.com/nittro/nette-bridges) repo.
