### ISSUE TITLE
Dynamic snippets

### ISSUE THREAD

**Issue by Kaliver88** [nittro/nittro#29]
Hi,

I have problem with redraw one item of list.

**Component PrinterPhotos**
**template**

```
<div n:snippet="printerPhotosContainer" n:dynamic="thumbnail-\d+" class="printer-photos nittro-snippet-container" data-dynamic-element="div.photo" >
    {foreach $photos as $photo}
        <div id="snippet-printerPhotos-thumbnail-{$photo['id']}" n:class="photo, nittro-transition-fade" >
            {* some conent here *}
        </div>
    {/foreach}
</div>
```

**control**

```
public function onAddPhotoToPositionEvent(AddPhotoToPositionEvent $addPhotoToPositionEvent) 
    {
        $item = $addPhotoToPositionEvent->getPhoto();
        $photos = $this->getPhotos();
        
        $this->getPresenter()->postGet('this');
        $this->redrawControl('printerPhotosContainer');
        
        $this->photos = [ $photos[$item->id] ];
    }
```

The payload of this code is:

```
{
    "snippets": {
        "snippet--editor": "",
        "snippet-printerPhotos-printerPhotosContainer": ""
    }
}
```

How can i do redraw only one item, not full list? Thanks

**Comment by jahudka** [comment]
Hi, I see a couple of issues with the code you posted:
- in your component's template the top-level DIV is an actual snippet, but the DIVs rendered in the foreach loop just have _snippet-like_ IDs - they're not actually snippets, there's no `n:snippet` macro on them - so the first thing to do would be to change them to something like this:

```latte
<div n:snippet="thumbnail-{$photo['id']}" n:class="...">
```

The rest of the code should work as intended, except for the `$photos = $this->getPhotos()` line you have in your event handler - if your code does what I think it does there should be no need to load all the photos, and depending on the logic of the `$this->getPhotos()` method and the logic for injecting photos into the template this might also be part of why the whole list gets re-rendered. Is the `$photos` array indexed by the photo ID? Is the value obtained from `$photos[$item->id]` different from `$item`? Should it be? Questions, so many questions ;-)

**Comment by Kaliver88** [comment]
> Hi, I see a couple of issues with the code you posted. In your component's template the top-level DIV is an actual snippet, but the DIVs rendered in the foreach loop just have snippet-like IDs - they're not actually snippets, there's no n:snippet macro on them - so the first thing to do would be to change them to something like this:

Yes, you're right. I used snippet-like IDs in the foreach loop intentionally.

That line of code
`<div n:snippet="thumbnail-$photo['id']" n:class="...">`

generate the notice for me:
`Notice: Use of undefined constant thumbnail - assumed 'thumbnail'`

The code `<div n:snippet="'thumbnail-' . $photo['id']" n:class="...">` fixed notice and behavior of dynamic snippet.

Thanks for your help.

**Comment by jahudka** [comment]
Great :-) glad it works.
