### ISSUE TITLE
Transition inherits duration from animation/transition of CSS loader

### ISSUE THREAD

**Issue by studna** [nittro/nittro#3]
I guess it's a feature, but it should be documented somewhere. I have own CSS loader with 2s animation and [this line](https://github.com/nittro/nittro/blob/master/dist/js/nittro.full.js#L4877) caused me lot of pain until I figured out why snippet rendering takes too long (2s after response). So I've to create an element inside the loader. Appling animation to this element (instead loader itself) solves this issue.

Maybe there should by some way how to set transition length globally or break transition on response.

**Comment by jahudka** [comment]
Hi, thanks for the report, I almost understand what your issue is, but I'm not entirely sure - can you please provide a code snippet clarifying your DOM structure and perhaps the code used to start the request if it's in any way custom?

**Comment by studna** [comment]
Sure, here it is. 

```
// CSS
#ajax-loader { animation: ownLoaderAnimation 2s linear infinite;  }

// HTML
<div id="ajax-loader"></div>
<a class="ajax">Some link</a>

<script id="nittro-params" type="application/json">
        {
            "page": {
                "whitelistLinks": true,
                "whitelistForms": false,
                "defaultTransition": "#ajax-loader"
            }
        }
</script>
```

I dont use custom requests or any - just the library as it is.

**Comment by jahudka** [comment]
Sorry for the delay.. Ok, and how do you show / hide the #ajax-loader div? ... anyway, looks to me as though you're missing the core concept behind transitions - they have 3 phases. There's the "out" phase, which occurs right after the user clicks a link or submits a form; Nittro waits for all transitioning elements to complete the "out" phase before doing anything else, that's the code you linked to earlier. Then there's the "middle" phase, which starts after all transitioned elements finished transitioning and lasts until the AJAX request completes and the payload is processed and all snippets applied etc., and lastly there's the "in" phase, which usually works like the "out" phase in reverse.

So your spinner animation should probably only be applied in the "middle" phase and you could have a short "out" and "in" phases which quickly show / hide the spinner, respectively.

**Comment by studna** [comment]
I see, now I get it. I've removed ".transition-out" (which handles displaying loader and its animation too) selector and it works fine now. Many thanks for explaining these transitions!

**Comment by jahudka** [comment]
You're quite welcome :-)
