### ISSUE TITLE
how to get all data from server?

### ISSUE THREAD

**Issue by vylink** [nittro/nittro#30]
Hi,

I'm trying to get all data returned by the server after every Ajax request. Is there some kind of ‘complete’, or ‘success’ callback including data object form the server?

It is more or less what is @mabar asking on https://github.com/nittro/nittro/issues/22

**Comment by vylink** [comment]
Hi @jahudka , many thanks for your answer. It will be great to create some very basic documentation/tutorial of how to use agents to prevent some default lifecycle actions for example ...(conditional preventing some snippets redrawing for some cases, or so.). I'm trying to implement this kind of logic into my project, so I will be maybe able to help about it. I can start with some basic wiki, but it will need your review for sure.

**Comment by jahudka** [comment]
@vylink hi, you're welcome! Unfortunately the cookbook I have in mind is a pretty complex beast and I just don't have enough time to work on it these days.. so any initiative on your or anyone else's part is most welcome! And of course I'd be happy to help with anything, be it solutions to specific problems or review of the solutions you come up with. Shoot me an email at me@subsonic.cz any time :-)
