### ISSUE TITLE
Nittro + Webpack

### ISSUE THREAD

**Issue by vojtamares** [nittro/nittro#36]
Hi, 

I am using webpack for building assets, can I use nittro with webpack? If so, how? Is there an example out there?

(I am new into JS world so I am sorry if this question is common and the solution is trivial)

**Comment by jahudka** [comment]
Hi, there is currently no official webpack integration available - I don't use webpack personally and I don't know enough about it to implement it. You can either switch to Gulp and use the [`gulp-nittro` plugin](https://github.com/nittro/gulp) or you can try implementing it yourself, in which case you can make use of the Nittro builder - it's part of the `nittro` npm package and it's used internally by the `gulp-nittro` plugin - its purpose is to resolve the passed configuration into an ordered list of files to be included in the build and optionally to generate a bootstrap script. Maybe that's something webpack could work with.. The API is pretty simple:

```js
const Builder = require('nittro');

const builder = new Builder({
    // for the list of available options consult https://github.com/nittro/gulp#options
});

var scripts = builder.getFileList('js');
var styles = builder.getFileList('css');
```

Most Nittro builds will need a bootstrap script - this is where the DI container is created, similarly to a `bootstrap.php` script you probably have somewhere in your Nette application. If you wish to have the builder generate a bootstrap script for you based on the Nittro components included in the build, you can pass `true` or an object with additional options as the `bootstrap` option when creating the Builder instance; in that case the generated list of `js` files will include `__bootstrap-generated.js`, which you then need to resolve to actual source code using the `builder.buildBootstrap()` method. Check out the [source of the Gulp plugin](https://github.com/nittro/gulp/blob/master/index.js) - it's rather a simple one to give you a starting point ;-)

**Comment by vojtamares** [comment]
After some thoughts on this, I decided to give a try to Vue.js for frontend and design just an backend API to fetch data from. 

Thank you for you answer and time :-)

**Comment by jahudka** [comment]
You're welcome, sad to see you go, but I understand :-) have fun with Vue!
