### ISSUE TITLE
Bower is no longer supported

### ISSUE THREAD

**Issue by camohub** [nittro/nittro#38]
Hi, as you know bower is no longer supported. I am using npm to download packages. But Nitro creates me a lot of packages and no compilated min files. I dont see any compilation documentation so my question is how to make nitro.min.js file what are the relations between packages and so.... Thanks a lot.

**Comment by jahudka** [comment]
Hi, to compile Nittro, you'll need a couple more things than just the `nittro` NPM package. Here are some pointers:
https://github.com/nittro/gulp - the `gulp-nittro` package, check out the readme and example config there
https://github.com/nittro/nittro/wiki/Nittro-packages - brief description of individual Nittro packages
https://github.com/nittro/nittro/wiki/Nette-bridges - backend integration
https://github.com/nittro/nittro/wiki/Controlling-Nittro-behaviour and https://github.com/nittro/nittro/wiki/Quick-reference - configuration

If you want a full example of how to create your own Nittro build toolchain, take a look at this project:
https://github.com/jahudka/nittro-project
It's basically a Nette skeleton project with Nittro and some scaffolding (mostly for an admin section). Look at the scripts in the `gulpfile.js` folder and the dependencies listed in `package.json`, that should get you started.

**Comment by camohub** [comment]
I dont use Gulp. If you are able to make bower package you should be able make a NPM package. I am sorry this seem to be useless.

**Comment by jahudka** [comment]
Sorry if you feel that way, but that's the way it is. With the way Nittro is designed you _should_ use a custom build with either Grunt or Gulp. For small projects you can get away with the [online builder](https://nittro.org/download), but even that uses Gulp behind the scenes. Or you can always use [Naja](https://naja.js.org/) and jQuery. But there aren't, and won't be, full compiled packages of Nittro available via NPM.
