### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by JanGalek** [nittro/nittro#6]
## Czech
Narazil jsem na problém, když mám
## English
I have a problem, when I have

`<a href="{plink '//:Feed:Rss:default', locale => $locale}" target="_blank" type="application/rss+xml">...</a>` 

## Czech
tak nittro změní url, ale měl by spíše otevřít nové okno.

## English
then nittro change url, but then should open a new window.

**Comment by jahudka** [comment]
### Czech

Pardon, teď jsem se tomu nějakou dobu vůbec nestíhal věnovat, děkuji za report, opravím :-)

### English

Sorry, I didn't have much time for nittro lately, thanks for the report, I'll fix it :-)
