### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by f3l1x** [nittro/nittro#8]
Could you please add this package as composer package? 

Therefore is still 0 downloads at componette portal. (https://componette.com/nittro/nittro/).

Thanks. :-)

**Comment by jahudka** [comment]
Hi, umm, sorry, I kind of completely forgot about this.. Well the thing is, I'm not sure Nittro should _have_ a Composer package - it's not a PHP library after all. I seriously doubt anyone would put their `vendor` folder within their document root, so if you were to install Nittro as a Composer package, you'd still need to either manually copy the JS and CSS files from the package (and why not just download the ZIP if that's the case) or you'd need some kind of build toolchain that would do that automatically (and that most probably means Gulp or Grunt or Webpack or something like that, which in turn means you likely already need Node.js and NPM, and that means you can and should get Nittro from NPM). Is there any use-case for a Composer package?

**Comment by f3l1x** [comment]
You're right. I think this issue useless at this moment. I'm closing it.
