### ISSUE TITLE
Backend redirect

### ISSUE THREAD

**Issue by misaon** [nittro/nittro#9]
Lze nějakým způsobem v signálu provést "redirect" na jiný presenter, typický příklad: po odeslání formuláře přesměrovat ajaxem na jiný presenter s výpisem všech článků..
Díky moc.

**Comment by jahudka** [comment]
Tak určitě, třeba `$presenter->redirect()` :-) Nette už odpradávna redirect při ajaxovém requestu posílá v payloadu místo jako HTTP 302 + Location, takže na backendu není potřeba nic zvláštního řešit. Na frontendu pak taky ne, protože Nittro samo rozpozná, že v payloadu dostalo redirect, a pokud splňuje same-origin policy, normálně ho načte; pokud by redirect nešlo načíst AJAXem (např. protože je z jiného originu), Nittro udělá redirect pomocí `document.location.href`.

Pak je tu ještě druhá metoda jak pracovat s redirecty v nittru - tzv. "POST-GET" odpověď. Často se stane, že bys v nějaké akci při neajaxovém požadavku potřeboval udělat redirect, ale není potřeba ho dělat, když jde požadavek AJAXem (protože v takovém případě má aplikace plnou kontrolu nad tím, co přesně uloží do historie prohlížeče, a tak není třeba dělat redirect, aby se zabránilo dvojímu odeslání dat atd.). V takové situaci stačí v payloadu říct Nittru že má do historie uložit jinou adresu než na kterou request posílalo (vpodstatě jako kdyby došlo k redirectu), ale zároveň aplikace může rovnou nechat vyrenderovat snippety - ušetří se tak jeden další AJAX request pro ten redirect.

Mrkni třeba sem: https://gist.github.com/jahudka/6626d60d0337025b4185a881f966b5c7 - používá se tam Nittro base presenter z nittro/nette-bridges, ale všechno co dělá si můžeš buď napsat sám, nebo přidat jen traitem. Důležitej je řádek 47 v kódu toho presenteru - `$this->postGet('this');` - to je právě metoda z Nittro presenter traitu která má stejné parametry jako `$presenter->redirect()`, ale chová se tak, že redirectuje jen při neajaxovém requestu. Efektivně při neajaxovém requestu tak ukončí zpracování presenteru a odešle odpověď klientovi. Při ajaxovém requestu jen přidá do payloadu `$payload->postGet = true;` a `$payload->url = $this->link($target, $args);`, a **neukončí** zpracování presenteru - takže můžeš vklidu nakrmit šablony, invalidovat snippety a pokračovat s renderingem. Výhodou je kromě ušetřeného requestu při redirectu taky to, že v ten moment máš aplikaci v nějakým stavu, kterej by sis jinak musel pamatovat - například jsi právě přidal novou položku do nějakýho seznamu a chtěl bys, aby se přidala i na frontendu - tak z těch položek uděláš dynamický snippety a po přidání necháš seznam vyrenderovat jen s tou jednou novou položkou, kterou navíc po uložení do modelu pravděpodobně budeš mít pohodlně po ruce.

A pak je ještě jedna důležitá otázka, kterou je občas potřeba si položit, a to je, zda vůbec dává smysl vytvářet po některejch akcích nový záznamy v historii - třeba když máš na homepagi box pro subscribnutí k nějakýmu newsletteru, dává spíš smysl po odeslání překreslit jen ten box a do historie nic nedávat, protože kam by tady uživatel šel "zpět", když z jeho úhlu pohledu neopustil úvodní stránku? To se dá udělat data atributem `data-history="false"` na odkazu nebo formuláři, kterej chceš do historie neukládat. (Teda určitě to jde v nittro#master, v 1.9.* to ještě nebylo mám dojem.)

**Comment by jahudka** [comment]
A ještě mě teď napadla jedna interpretace tvého dotazu, pro situaci po odeslání formuláře / zpracování signálu kdy potřebuješ udělat *lokální* redirect, ale nechceš, aby ho Nittro načetlo AJAXem (protože například potřebuješ po loginu překreslit celou site včetně navigace kterou nemáš v snippetu atd.) - pak můžeš do payloadu přidat `$payload->allowAjax = false;` a Nittro udělá redirect pomocí `document.location.href`.

Navíc nové Nittro v masteru umí ještě jednu věc a to je zpracovat z jedné odpovědi jak redirect, tak snippety - takže například můžeš po přidání položky do košíku invalidovat widget košíku v liště, aby zobrazil novou cenu nákupu, a zároveň poslat redirect na presenter / akci, která přerenderuje nějakej hlavní snippet (např. "content") a zobrazí v něm obsah košíku a tlačitko pro checkout. Na to zatím v nittro/nette-bridges není helper, musel by sis ručně zapsat `$payload->redirect = $presenter->link('nekde:neco')` a pak můžeš invalidovat snippety který má překreslit první request.

**Comment by misaon** [comment]
Kamaráde, tak takhle dokonalou a obsáhlou odpověď na dotaz jsem už dlouho nedostal, každopádně díky moc 👍 

Já jen že když jsem z handlu poslal $this->redirect("Article:list");, přesměrovalo mě to klasicky neAjaxovým způsobem. Z dokumentace a praxe vím, že všechny lokální odkazy bere Nittro jako ajaxové a když se k tomu šupne i hezký fade efekt, vypadá to skvěle, avšak v mém případě vždy proběhne neajaxový redirect, možná něco dělám špatně, možno špatný zápis.. , nebo je tohle Nittro správné chování?

```
public function handleTest(int $id) {
    $article = $this->context->table("article")->select("name")->get($id);

    if ($article) {
        $this->redirect("Article:show", ["name" => $article->name]);
    }
}
```

Ještě jednou díky za tvou pomoc 😃

**Comment by jahudka** [comment]
Není za co, naopak já dík za report etc., nemám k Nittru úplně tolik zpětný vazby jak bych si představoval, takže všechno vítám :-)

Pokud ti klasický `$this->redirect('...')` dělá neajaxovej redirect, může to teoreticky bejt tím, že máš zapnutý whitelistování redirectů. Pak by Nittro automaticky předpokládalo, že výchozí chování je tvrdej redirect, a až když dáš v payloadu `$payload->allowAjax = true`, povolil by se pro ten danej redirect AJAX. Zkus před `$this->redirect('...')` dát `$this->payload->allowAjax = true;`. Popravdě už si nepamatuju, jaký bylo výchozí chování v 1.9.*. Pokud by to bylo tím, můžeš si přepnout `whitelistRedirects: false` v bootstrapu a pak naopak platí to co jsem popsal výše - tj. redirect se automaticky dělá AJAXem když to jde, a pro lokální redirecty který chceš natvrdo si přidáš do payloadu to `$payload->allowAjax = false`.

Btw, chápu to správně, že používáš 1.9.*?

**Comment by misaon** [comment]
Tak měl si pravdu, moje verze je 1.9.6 (poslední stable release).
Při nasazování na dev projekt se všechno hezky rozběhlo, jen data-ajax="false" u odkazů nefunguje. Mám pocit že docs na stránkách nepatří k aktuální verzi co je na boweru/packagists.
 Případně bych rád otestoval master verzi nebo alespoň 2.0-RC3, avšak v automatizovaných nástrojů typu gulp nejsem nějak zběhlý.
Chci tě poprosit o nový release, případně kdy bude s vygenerovanými CSS a JS soubory, nebo nějaký rychlý tip, jak si tyto soubory vygenerovat sám.

Jinak ještě jedna věc, když lokálním odkazem přejdu na jiný presenter, kde je jQuery plugin, logicky se nezinicializuje. Obecně to lze řešit nějakým podobným způsobem.
```
$("#LangTable").on("click",".deletelanguage", function(){
  alert("success");
});
```
Zvědavost mi však nedá a zajímalo by mě, jestli něco podobného neumí globálně Nittro samo.

Díky moc :)

**Comment by jahudka** [comment]
`data-ajax` u odkazů je právě až v 2.0, v 1.9.* se to dělalo pomocí class `ajax` nebo `noajax` (podle toho, jestli jsi měl zapnutý whitelistování linků / formů nebo ne).

Naučit se ten gulp je fajn, protože ti dovolí snadno spojit všechny javascripty do jednoho, kterej pak můžeš načíst asynchronně a zrychlit tak o něco celej web. A zrovna gulp se učí celkem snadno, protože ten "gulpfile", kterým se definujou jednotlivý tasky, je prostě jenom javascript ve kterým definuješ pár funkcí. Takže rozhodně doporučuju to zkusit, dlouhodobě je to fakt fajn. Jakmile budu ready vydat dvojku, z webu půjdou samozřejmě stahnout hotový buildy, chtěl bych tam mít něco jako má jQuery UI, kde si naklikáš jaký komponenty chceš a stáhneš si přímo custom build přesně podle svejch potřeb.

Pokud to s tím masterem chceš zkusit i tak, asi nejjednodušší je to fakt přes ten gulp, musel bys mít nainstalovaný nodejs / npm a bower, ale pak je to na tři příkazy v terminálu a upravení jednoho souboru, pokud chceš, klidně tě tím provedu, ale asi to bude pohodlnější řešit třeba po mailu, nebo pokud jsi na slacku Péhápkáři :-)

Co se týče toho volání skriptů na ajaxem načtenejch stránkách, záleží na tom, jestli ten incializační skript je součástí nějakýho velkýho balíku skriptů kterej načítáš při načtení stránky, nebo jestli to je inline javascript přímo v šabloně. Pokud je to to první, musíš ten kód volat v handleru události `update` spouštěný na nittro page service (a nezapomeň nějak ošetřit, aby se ten "click" handler na elementu #LangTable neduplikoval při každým ajaxovým requestu - tj. třeba tam před to přidej `$('#LangTable').off('click');`). A pokud tu inicializaci děláš v inline javascriptu, přečti si tohle: https://github.com/nittro/nittro/wiki/_stack

**Comment by misaon** [comment]
Díky za ochotu, můžeme se bavit skrz mail (viz. můj profil).
Byl bych rád kdyby si mi poradil s postupem při zavedení gulp a příklad použití inicializace jQuery v metodě load třeba u pluginu [summernote](http://summernote.org/).

```
$(document).ready(function() {
  $('.summernote').summernote();
});
```

Díky moc :)
